application:
  max-allowed-books: 2
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book_registry
    username: root
    password: 11235
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

